from mlproject.pipeline.st_01_data_ingestion import DataIngestionTrainingPipeline
from mlproject.pipeline.st_02_data_validation import DataValidationTrainingPipeline
from mlproject.pipeline.st_03_data_transformation import DataTransformationTrainingPipeline